defaults: &defaults
  data_api:
    server: 'some_server'
    port: 8080
    version: 'v1.0'

  log:
    level: :debug
    stream:
      stdout: true
      files:
      format:

  workers:
    count: 8

test:
  <<: *defaults

production:
  <<: *defaults
