defaults: &defaults
  data_api:
    protocol: 'http'
    server: 'some_server'
    port: 8080
    version: 'v1.0'
    resources:
      keys_list: 'push_notification_target/describe_keys'
      tokens_list: 'osn_recepients/list_tokens'
      delete_token: 'osn_recepients/delete_recipient'

  log:
    level: :debug
    stream:
      stdout: true
      files:
      format:

  service:
    apns:
      gateway: 'gateway.push.apple.com'
      port:  2195
      retries:  3
    feedback:
      gateway:  "feedback.push.apple.com"
      port: 2196
      retries:  2

  mysql:


  threads:
    workers: 4
    listeners: 8

test:
  <<: *defaults

production:
  <<: *defaults
