:test:
  :database:
    :name: 'push_notifications-test'
    :tables:
      :targets:
        :name: 'push_notification_targets'
      :keys:
        :name: 'push_notification_keys'

  :log:
    :level: :debug
    :stream: {
      stdout: true
      files:
      format:
    }

  :workers:
    :count: 8

:production:
  :database:
    :name: 'push_notifications'
    :tables:
      :targets:
        :name: 'push_notification_targets'
      :keys:
        :name: 'push_notification_keys'

  :log:
    :level: :warn
    :stream: {
      stdout: false
      files: ['production.log']
      format:
    }

  workers:
    count: 16
