test:
  database:
    name: push_notifications-test
    tables:
      targets:
        name: push_notification_targets
      keys:
        name: push_notification_keys

  clean:
    period: 24 # hours

production:
  database:
    name: push_notifications
    tables:
      targets:
        name: push_notification_targets
      keys:
        name: push_notification_keys

  clean:
    period: 24 # hours
