:test:
  :database:
    :name: 'push_notifications-test'
    :tables:
      :targets:
        :name: 'push_notification_targets'
      :keys:
        :name: 'push_notification_keys'

  :log:
    :level: :debug
    :stream: {
      stdout: true
      files: []
      format:
    }

  :clean:
    :period: 24 # hours

:production:
  :database:
    :name: 'push_notifications'
    :tables:
      :targets:
        :name: 'push_notification_targets'
      :keys:
        :name: 'push_notification_keys'

  :log:
    :level: :warn
    :stream: {
      stdout: false
      files: []
      format:
    }

  :clean:
    :period: 24 # hours
